// assumptions.js — every modelling assumption, surfaced in the UI.
// Each entry mirrors a labelled ASSUMPTION comment in the source module.

export const ASSUMPTIONS = [
  { area: "Pipeline", text: "STRICT LAYER ORDER — terrain → settlements (+ provisional corridors) → roads → load → MEMBERSHIP (customers → feeders → zone subs, decided BEFORE any routing) → sub siting → feeder routing → subtransmission (visual only). A validation pass regenerates on a deterministic retry seed when a rule fails, and after 4 attempts keeps the best attempt with reasons reported (never a hard fail). (main.js, membership.js)" },
  { area: "Geography", text: "30 × 30 km invented map on a 200 m grid; sea along one seed-chosen edge; one river traced border-to-ocean by noisy steepest descent (60–140 m wide). Buildable = main landmass, not water, slope < 0.35 m/m. No real data. (terrain.js)" },
  { area: "Settlements", text: "Sites scored on flatness, a coastal↔river blend (Inland slider), river-mouth proximity, and junctions of a provisional least-cost corridor skeleton (anchors ↔ map-edge exits) that later seeds the arterials. Populations follow Zipf rank-size (pop ∝ 1/rank^1.05): one dominant, 2–3 medium, rest small; σ ∝ √pop; spacing scales with town size (2.2 km + 1.6×(σi+σj)); both river banks settled when land allows. (density.js)" },
  { area: "Roads", text: "Arterials = corridor skeleton + MST between towns + one loop, A*-routed with slope² cost; sea impassable; first river crossing builds a bridge (28×), later roads reuse it. Urban grids: spacing scales with population (120–170 m), orientation snapped to the local coast tangent / river axis / terrain contour — never global north — with a regular core fraying to irregular edges. Rural roads: spurs off arterials into flat country (some fork); rural LOAD follows roads, not vice versa. (roads.js)" },
  { area: "Load", text: "Density = per-town Gaussians (uniform peak, area ∝ population) + rural background decaying with ROAD distance (sparse rural load along roads), × fBm noise from the terrain's noise family. Customers sampled from this field on buildable land only, then snapped to the road graph. (density.js, customers.js)" },
  { area: "Electrical", text: "Distribution transformers: greedy capacitated clustering, ≤ 50 customers, within 500 m urban / 1500 m rural. LV below the TX not modelled. (network.js)" },
  { area: "Electrical", text: "Membership first: customers classified urban/rural by LOCAL DENSITY (≥ 60 cust/km² within 500 m — absolute, so a denser world classifies more urban); customers → feeders by road-capacitated clustering (urban ≤ 700, rural ≤ 300 + 10 km road-extent cap, runts < 150 merged); feeders → zone subs by shared road-graph Voronoi boundary (NOT straight-line), ≤ 8 feeders per sub. (membership.js)" },
  { area: "Electrical", text: "Zone subs sit at the LOAD-WEIGHTED CENTROID of their feeder group, nudged to the nearest arterial/collector road node with gentle slope — never a geometric centre or town marker. (network.js)" },
  { area: "Electrical", text: "Routing LAST, honouring membership: one Dijkstra tree per sub over the roads serving ONLY its member load; a sub claims road nodes in its own catchment only, and stretches through a foreign catchment are charged as EXPRESS exposure (the second circuit on a shared road). Every feeder is a single contiguous subtree — asserted. Validate + repair (≤ 3 passes, outcomes in Checks, all caps tunable): trunks ≤ 20 km, transit on another sub's actual network ≤ 2.5 km, count/extent caps re-split or re-grouped for affected members only. (network.js, reliability.js)" },
  { area: "Electrical", text: "Line sections in cells above the density threshold are UNDERGROUND cable (drawn dashed), the rest overhead. λ defaults: 0.10 OH / 0.03 UG faults/km/yr, both adjustable; repair is a flat 120 min for both — a simplification that flatters cable repairs. (network.js, reliability.js)" },
  { area: "Subtransmission", text: "GXP on a flat map-edge cell near the load centroid (prefers road corridors). Lines GXP → subs are least-cost A* (slope penalised, ocean blocked, river crossings 6×, road corridors rewarded); adjacent subs share trunk corridors before branching (0.35× on used cells) and one inter-sub tie is routed to AVOID the trunks. VISUAL ONLY — a check asserts SAIDI and network structure are unchanged by (re)building it. (subtx.js)" },
  { area: "Reliability", text: "Fault rates uniform within each line type — no weather, vegetation or asset-age variation. Debug mode can double λ on one branch. Unrestored outage = crew travel from the zone sub at 50 km/h along roads + flat 120 min repair. (reliability.js)" },
  { area: "Reliability", text: "Sectionalising: open deepest upstream switch, reclose the tripped device; everyone else in the tripped zone restored after a flat 45 min (flat time makes greedy placement provably monotone). Reclosers are ideal protection: upstream customers see NO sustained interruption; momentaries (SAIFI/MAIFI) not modelled. Radial — no backfeed. Baseline is device-free. (reliability.js)" },
  { area: "Reliability", text: "Devices-for-improvement table: fewest devices of each kind, placed greedily from a DEVICE-FREE network, to cut SAIDI by ≥ 10/25/50%; caps 60 SW / 30 RC match the UI inputs. (main.js)" },
  { area: "Visual", text: "SAIDI heat layer shades each customer cell by the serving feeder's customer-minutes, normalised to the current worst feeder (dark = worst) — a view of the league table, not an input. (render.js)" },
  { area: "General", text: "Plausible, not optimal — greedy/heuristic everywhere, matching the untidy way real networks accrete. Seeded and deterministic throughout, including validation retries." },
];
