// assumptions.js — every modelling assumption, surfaced in the UI.
// Each entry mirrors a labelled ASSUMPTION comment in the source module.

export const ASSUMPTIONS = [
  { area: "Pipeline", text: "STRICT LAYER ORDER — terrain → settlements (+ provisional corridors) → roads → load → transformers → zone subs (grown, sited, then capacity-balanced) → busbar-branch feeders (no express runs; over-cap branches spawn subs, close subs merge) → PRUNE (feeders under 20 customers removed with their customers and TXs, network rebuilt from the survivors) → subtransmission (visual only). Sub and feeder counts EMERGE from simple rule caps. A validation pass regenerates on a deterministic retry seed when a rule fails, and after 4 attempts keeps the best attempt with reasons reported (never a hard fail). (main.js, membership.js)" },
  { area: "Geography", text: "100 × 70 km invented map on a 200 m grid (500 × 350 cells, landscape aspect for the browser); sea along one seed-chosen edge; one river traced border-to-ocean by noisy steepest descent (60–210 m wide). Buildable = main landmass, not water, slope < 0.35 m/m. No real data. (terrain.js)" },
  { area: "Settlements", text: "EXPLICIT three-tier hierarchy (targets as shares of sampled customers, so at 50k): ONE large town ≈ 40% (~20,000), each small town 2–4% (1,000–2,000, count set by the slider), and 6–10 rural settlements at 0.4–1% (200–500) — kernel weights are set so realised counts hit the targets, and the rural background gets the remainder. Sites scored on flatness, a coastal↔river blend (Inland slider), river-mouth proximity, and junctions of a provisional least-cost corridor skeleton (anchors ↔ map-edge exits) that later seeds the arterials. σ ∝ √customers (uniform peak density); spacing scales with town size (5 km + 1.6×(σi+σj)); both river banks settled when land allows. (density.js)" },
  { area: "Roads", text: "Inter-town network = corridor skeleton + MST over ALL towns and settlements + 2-nearest-neighbour links (within 45 km), so towns connect in a web with loops, not a bare tree; links touching a rural settlement are collectors, town↔town links are arterials. All A*-routed with slope² cost; sea impassable; first river crossing builds a bridge (28×), later roads reuse it. Urban streets: an organic lattice — spacing scales with population (120–170 m), orientation snapped to the local coast tangent / river axis / terrain contour, every point wobbles, fraying starts near the core, and ~7% of streets drop out (dead ends). Rural roads: spurs off arterials every ~1–1.6 km (many fork), then nearby dead ends are linked into a sparse web of back roads; rural LOAD follows roads, not vice versa. (roads.js)" },
  { area: "Load", text: "Density = per-town kernels — Gaussian core + exponential shoulder, so density eases through a peri-urban fringe instead of cliff-edging at the town boundary (mass-compensated, area ∝ population) — + rural background decaying with ROAD distance, + an off-road shoulder (farms up to ~6 km past the road end), × fBm noise. 50 000 customers (fixed) sampled from this field on buildable land, then snapped to the road graph; those landing on feeders under 20 customers are pruned, so the served count emerges slightly lower. (density.js, customers.js, main.js)" },
  { area: "Electrical", text: "Distribution transformers: the TX sits AT a seed customer (fixed pole site) and gathers neighbours within 500 m, up to 100 customers — the ≤ 500 m rule holds exactly by construction. Rural TXs max out on distance, urban on count. A TX more than 400 m from any road connects by a LINE EASEMENT — a straight cross-country span to the nearest road node or a nearer easement node (spans daisy-chain up remote valleys) — so rural feeders may leave the road corridor. Easements never span sea or lakes; river spans are allowed (towers, not bridges). Crew travel is charged along the line route — an approximation. LV below the TX not modelled. (network.js, membership.js)" },
  { area: "Electrical", text: "Zone subs: TXs cluster by road-Dijkstra growth (≤ 50 km or ≤ 4,000 customers, no minimums); each sub is sited at its cluster's LOAD-WEIGHTED CENTROID nudged to an arterial/collector node. Every TX then joins its road-nearest sub via an ADDITIVELY WEIGHTED graph Voronoi: over-cap subs bid their boundary out, starved subs bid back in, and a cell that stays over cap spawns a new sub in its far half — the sub count truly emerges. (network.js)" },
  { area: "Electrical", text: "Feeders are the BUSBAR BRANCHES of each sub's shortest-path tree — one feeder per branch, NO deep cuts and NO express runs (no parallel circuits sharing a trunk). A branch that would exceed ≤ 1,000 customers or ≤ 50 km REACH (line distance sub → farthest point; total conductor unbounded, feeders branch) spawns a NEW sub at the branch's far-half load centroid instead, and stations within 6 km of each other are MERGED when their combined load fits a couple of feeders — so subs sit central to the feeders they serve. A feeder still carrying fewer than 20 customers is PRUNED — the feeder, its transformers AND its customers are removed (uneconomic to reticulate) and the network is rebuilt from the survivors. Rule residues (a dense-town road carrying > 1,000 on one branch) are CHECKED and reported, never absorbed. (network.js, main.js)" },
  { area: "Electrical", text: "Line sections in cells above the density threshold are UNDERGROUND cable (drawn dashed), the rest overhead. λ defaults: 0.08 OH / 0.02 UG faults/km/yr, both adjustable; repair is a flat 120 min for both — a simplification that flatters cable repairs. (network.js, reliability.js)" },
  { area: "Subtransmission", text: "GXP on a flat map-edge cell near the load centroid (prefers road corridors). Lines GXP → subs are least-cost A* (slope penalised, ocean blocked, river crossings 6×, road corridors rewarded); adjacent subs share trunk corridors before branching (0.35× on used cells) and one inter-sub tie is routed to AVOID the trunks. VISUAL ONLY — a check asserts SAIDI and network structure are unchanged by (re)building it. (subtx.js)" },
  { area: "Reliability", text: "Fault rates uniform within each line type — no weather, vegetation or asset-age variation. Debug mode can double λ on one branch. Unrestored outage = crew travel from the zone sub at 50 km/h along roads + flat 120 min repair. (reliability.js)" },
  { area: "Reliability", text: "Sectionalising: open deepest upstream switch, reclose the tripped device; everyone else in the tripped zone restored after a flat 45 min. Reclosers are ideal protection: upstream customers see NO sustained interruption; momentaries (SAIFI/MAIFI) not modelled; reclosers double as isolators for backfeed. BACKFEED: adjacent feeders share one normally-open tie (shortest unused road/easement edge ≤ 2 km, built in network.js); for a fault, every maximal device-bounded subtree below it that reaches a tie is re-energised from the neighbouring feeder at the same flat 45 min — tie capacity UNLIMITED and the neighbour assumed healthy (labelled simplifications). Greedy candidate gains are EXACT per-feeder re-evaluations, so placement stays provably monotone. Baseline is device-free. (reliability.js)" },
  { area: "Reliability", text: "Devices-for-improvement table: fewest devices of each kind, placed greedily from a DEVICE-FREE network, to cut SAIDI by ≥ 10/25/50%; caps 120 SW / 60 RC match the UI inputs. (main.js)" },
  { area: "Visual", text: "SAIDI heat layer shades each customer cell by the serving feeder's customer-minutes, normalised to the current worst feeder (dark = worst) — a view of the league table, not an input. (render.js)" },
  { area: "General", text: "Plausible, not optimal — greedy/heuristic everywhere, matching the untidy way real networks accrete. Seeded and deterministic throughout, including validation retries." },
];
